// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace cart {
inline int TEX[1] = {-1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[1] = {"common/atlas0.png"};
static const int NTEX = 1;
static const nova::Img IMG_BLOCK = {&TEX[0], 3757, 3, 128, 128, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_BRICK = {&TEX[0], 3635, 512, 240, 88, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_ORB = {&TEX[0], 3891, 3, 126, 126, 63.0f, 63.0f, 0.5000f};
static const nova::Img IMG_SPARK = {&TEX[0], 3507, 512, 122, 122, 61.0f, 61.0f, 0.5000f};
static const nova::Img IMG_RING = {&TEX[0], 3, 3, 256, 256, 128.0f, 128.0f, 0.5000f};
static const nova::Img IMG_PUFF = {&TEX[0], 3559, 3, 192, 192, 96.0f, 96.0f, 0.5000f};
static const nova::Img IMG_STREAK = {&TEX[0], 3881, 512, 80, 24, 40.0f, 12.0f, 0.5000f};
static const nova::Img IMG_LOGO_BLOCKFALL = {&TEX[0], 265, 3, 962, 241, 480.5f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_BRICKSTORM = {&TEX[0], 1233, 3, 1077, 241, 539.5f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_NEONSERPENT = {&TEX[0], 2316, 3, 1237, 241, 618.0f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_ASTRODRIFT = {&TEX[0], 3, 759, 1079, 240, 542.0f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_NOVALANCE = {&TEX[0], 3, 265, 1071, 241, 536.5f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_ALIENTIDE = {&TEX[0], 1080, 265, 908, 241, 458.0f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_HOPRUSH = {&TEX[0], 1088, 759, 845, 240, 422.5f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_MAZEMUNCH = {&TEX[0], 1994, 265, 1104, 241, 552.5f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_VOLTRALLY = {&TEX[0], 3, 512, 1013, 241, 504.5f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_GEMCASCADE = {&TEX[0], 1022, 512, 1170, 241, 587.0f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_CITYSHIELD = {&TEX[0], 3104, 265, 984, 241, 493.0f, 117.0f, 1.0000f};
static const nova::Img IMG_LOGO_TURBOHORIZON = {&TEX[0], 2198, 512, 1303, 241, 653.0f, 117.0f, 1.0000f};
}  // namespace cart
