// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace nlart {
inline int TEX[1] = {-1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[1] = {"novalance/atlas0.png"};
static const int NTEX = 1;
static const nova::Img IMG_PLAYER = {&TEX[0], 339, 567, 288, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_DRONE0 = {&TEX[0], 3, 567, 162, 162, 81.0f, 81.0f, 0.5000f};
static const nova::Img IMG_DRONE1 = {&TEX[0], 171, 567, 162, 162, 81.0f, 81.0f, 0.5000f};
static const nova::Img IMG_DART = {&TEX[0], 633, 567, 198, 117, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_POD0 = {&TEX[0], 1527, 3, 198, 198, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_POD1 = {&TEX[0], 1731, 3, 198, 198, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_BOSS = {&TEX[0], 3, 3, 756, 558, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_PLANET = {&TEX[0], 765, 3, 756, 540, 0.0f, 0.0f, 0.5000f};
}  // namespace nlart
