// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace vrart {
inline int TEX[1] = {-1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[1] = {"voltrally/atlas0.png"};
static const int NTEX = 1;
static const nova::Img IMG_CORE = {&TEX[0], 89, 3, 64, 324, 32.0f, 162.0f, 0.5000f};
static const nova::Img IMG_SHELL = {&TEX[0], 3, 3, 80, 340, 40.0f, 170.0f, 0.5000f};
static const nova::Img IMG_BALL0 = {&TEX[0], 1409, 3, 110, 110, 55.0f, 55.0f, 0.5000f};
static const nova::Img IMG_BALL1 = {&TEX[0], 1525, 3, 110, 110, 55.0f, 55.0f, 0.5000f};
static const nova::Img IMG_HOT0 = {&TEX[0], 1641, 3, 110, 110, 55.0f, 55.0f, 0.5000f};
static const nova::Img IMG_HOT1 = {&TEX[0], 1757, 3, 110, 110, 55.0f, 55.0f, 0.5000f};
static const nova::Img IMG_BADGE = {&TEX[0], 159, 3, 222, 254, 111.0f, 127.0f, 0.5000f};
static const nova::Img IMG_G0 = {&TEX[0], 387, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img IMG_G1 = {&TEX[0], 533, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img IMG_G2 = {&TEX[0], 679, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img IMG_G3 = {&TEX[0], 825, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img IMG_G4 = {&TEX[0], 971, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img IMG_G5 = {&TEX[0], 1117, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img IMG_GYOU = {&TEX[0], 1263, 3, 140, 140, 70.0f, 70.0f, 0.5000f};
static const nova::Img* const BALL[2] = {&IMG_BALL0, &IMG_BALL1};
static const nova::Img* const HOT[2] = {&IMG_HOT0, &IMG_HOT1};
static const nova::Img* const GLYPH[6] = {&IMG_G0, &IMG_G1, &IMG_G2, &IMG_G3, &IMG_G4, &IMG_G5};
}  // namespace vrart
