// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace atart {
inline int TEX[1] = {-1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[1] = {"alientide/atlas0.png"};
static const int NTEX = 1;
static const nova::Img IMG_ORB0 = {&TEX[0], 329, 3, 131, 125, 70.0f, 74.0f, 0.5000f};
static const nova::Img IMG_MANTIS0 = {&TEX[0], 3, 3, 158, 129, 79.0f, 61.0f, 0.5000f};
static const nova::Img IMG_JELLY0 = {&TEX[0], 603, 3, 128, 121, 64.0f, 53.0f, 0.5000f};
static const nova::Img IMG_SAUCER0 = {&TEX[0], 1053, 3, 250, 102, -1.0f, 1.0f, 0.5000f};
static const nova::Img IMG_ORB1 = {&TEX[0], 466, 3, 131, 125, 61.0f, 74.0f, 0.5000f};
static const nova::Img IMG_MANTIS1 = {&TEX[0], 167, 3, 156, 129, 78.0f, 61.0f, 0.5000f};
static const nova::Img IMG_JELLY1 = {&TEX[0], 737, 3, 128, 121, 64.0f, 53.0f, 0.5000f};
static const nova::Img IMG_SAUCER1 = {&TEX[0], 1309, 3, 250, 102, -1.0f, 1.0f, 0.5000f};
static const nova::Img IMG_CANNON = {&TEX[0], 871, 3, 176, 106, 7.0f, 6.0f, 0.5000f};
}  // namespace atart
