// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace mmart {
inline int TEX[4] = {-1, -1, -1, -1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[4] = {"mazemunch/atlas0.png", "mazemunch/maze_fill.png", "mazemunch/maze_glow.png", "mazemunch/maze_tube.png"};
static const int NTEX = 4;
static const nova::Img IMG_MUNCH0 = {&TEX[0], 587, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH1 = {&TEX[0], 721, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH2 = {&TEX[0], 855, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH3 = {&TEX[0], 989, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH4 = {&TEX[0], 1123, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH5 = {&TEX[0], 1257, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH6 = {&TEX[0], 1391, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH7 = {&TEX[0], 1525, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH8 = {&TEX[0], 1659, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH9 = {&TEX[0], 1793, 3, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH10 = {&TEX[0], 3, 177, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH11 = {&TEX[0], 137, 177, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH12 = {&TEX[0], 271, 177, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH13 = {&TEX[0], 405, 177, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH14 = {&TEX[0], 539, 177, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_MUNCH15 = {&TEX[0], 673, 177, 128, 128, 64.0f, 64.0f, 0.5000f};
static const nova::Img IMG_WISP0 = {&TEX[0], 3, 3, 140, 168, 70.0f, 88.0f, 0.5000f};
static const nova::Img IMG_WISP1 = {&TEX[0], 149, 3, 140, 168, 70.0f, 88.0f, 0.5000f};
static const nova::Img IMG_WISP2 = {&TEX[0], 295, 3, 140, 168, 70.0f, 88.0f, 0.5000f};
static const nova::Img IMG_WISP3 = {&TEX[0], 441, 3, 140, 168, 70.0f, 88.0f, 0.5000f};
static const nova::Img IMG_FRIGHT = {&TEX[0], 941, 177, 96, 72, 48.0f, 36.0f, 0.5000f};
static const nova::Img IMG_CRYSTAL = {&TEX[0], 1927, 3, 88, 104, 44.0f, 52.0f, 0.5000f};
static const nova::Img IMG_GEM = {&TEX[0], 807, 177, 128, 120, 64.0f, 60.0f, 0.5000f};
static const nova::Img IMG_MAZE_FILL = {&TEX[1], 0, 0, 1340, 1070, 0, 0, 1.0000f};
static const nova::Img IMG_MAZE_GLOW = {&TEX[2], 0, 0, 1340, 1070, 0, 0, 1.0000f};
static const nova::Img IMG_MAZE_TUBE = {&TEX[3], 0, 0, 2680, 2140, 0, 0, 0.5000f};
static const nova::Img* const MUNCH[16] = {&IMG_MUNCH0, &IMG_MUNCH1, &IMG_MUNCH2, &IMG_MUNCH3, &IMG_MUNCH4, &IMG_MUNCH5, &IMG_MUNCH6, &IMG_MUNCH7, &IMG_MUNCH8, &IMG_MUNCH9, &IMG_MUNCH10, &IMG_MUNCH11, &IMG_MUNCH12, &IMG_MUNCH13, &IMG_MUNCH14, &IMG_MUNCH15};
static const nova::Img* const WISP[4] = {&IMG_WISP0, &IMG_WISP1, &IMG_WISP2, &IMG_WISP3};
}  // namespace mmart
