// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace hrart {
inline int TEX[1] = {-1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[1] = {"hoprush/atlas0.png"};
static const int NTEX = 1;
static const nova::Img IMG_CAR_BODY = {&TEX[0], 263, 3, 144, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_CAR_TOP = {&TEX[0], 413, 3, 144, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_RACER_BODY = {&TEX[0], 563, 3, 144, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_RACER_TOP = {&TEX[0], 713, 3, 144, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_TRUCK = {&TEX[0], 863, 3, 432, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_DOZER = {&TEX[0], 1301, 3, 288, 144, 0.0f, 0.0f, 0.5000f};
static const nova::Img IMG_LOG_L = {&TEX[0], 1595, 3, 160, 144, 8.0f, 0.0f, 0.5000f};
static const nova::Img IMG_LOG_M = {&TEX[0], 1761, 3, 160, 144, 8.0f, 0.0f, 0.5000f};
static const nova::Img IMG_LOG_R = {&TEX[0], 3, 170, 160, 144, 8.0f, 0.0f, 0.5000f};
static const nova::Img IMG_PAD = {&TEX[0], 169, 170, 130, 132, 66.0f, 66.0f, 0.5000f};
static const nova::Img IMG_BOT = {&TEX[0], 133, 3, 124, 153, 62.0f, 85.0f, 0.5000f};
static const nova::Img IMG_BOT_HOP = {&TEX[0], 3, 3, 124, 161, 62.0f, 85.0f, 0.5000f};
static const nova::Img IMG_BOT_FLAT = {&TEX[0], 305, 170, 142, 62, 71.0f, 11.0f, 0.5000f};
static const nova::Img IMG_GEM = {&TEX[0], 1927, 3, 92, 108, 46.0f, 54.0f, 0.5000f};
}  // namespace hrart
