#!/usr/bin/env python3
"""Bakes the UI font (Fredoka SemiBold, SIL Open Font License, see OFL.txt) into two textures that
share one layout: assets/font.png (the letters) and assets/font_outline.png (the same letters with a
thick stroke, drawn underneath for outlined text). Writes engine/font_data.h with the metrics.
    python3 tools/font/make_font.py     (from the repo root)
Text is positioned by the top of its capitals: the engine puts the baseline at y + cap height."""
import os
import skia

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
EM = 128            # baked size; the engine scales from this
WEIGHT = 600
STROKE = 22         # outline width at EM size
PAD = STROKE // 2 + 3
FIRST, LAST = 32, 126
ATLAS_W = 1024


def typeface():
    tf = skia.Typeface.MakeFromFile(os.path.join(ROOT, "tools/font/Fredoka.ttf"))
    C = skia.FontArguments.VariationPosition.Coordinate
    coords = skia.FontArguments.VariationPosition.Coordinates([C(0x77676874, float(WEIGHT))])   # 'wght'
    fa = skia.FontArguments()
    fa.setVariationDesignPosition(skia.FontArguments.VariationPosition(coords))
    return tf.makeClone(fa)


def main():
    font = skia.Font(typeface(), EM)
    font.setEdging(skia.Font.Edging.kAntiAlias)
    font.setSubpixel(True)
    cap = font.getMetrics().fCapHeight
    glyphs = []
    for code in range(FIRST, LAST + 1):
        gid = font.textToGlyphs(chr(code))[0]
        adv = font.getWidths([gid])[0]
        b = font.getBounds([gid])[0]
        empty = b.width() <= 0
        glyphs.append(dict(ch=chr(code), gid=gid, adv=adv, b=b, empty=empty))
    # shelf-pack the padded cells
    x = y = rowh = 0
    for g in glyphs:
        if g["empty"]:
            g.update(x=0, y=0, w=0, h=0, xoff=0, yoff=0)
            continue
        b = g["b"]
        w = int(b.width() + 2 * PAD + 2)
        h = int(b.height() + 2 * PAD + 2)
        if x + w > ATLAS_W:
            x, y, rowh = 0, y + rowh + 1, 0
        g.update(x=x, y=y, w=w, h=h, xoff=b.left() - PAD - 1, yoff=b.top() - PAD - 1 + cap)
        x += w + 1
        rowh = max(rowh, h)
    height = y + rowh + 1
    for outline in (False, True):
        surf = skia.Surface(ATLAS_W, height)
        c = surf.getCanvas()
        c.clear(skia.Color4f(1, 1, 1, 0))
        p = skia.Paint(AntiAlias=True, Color=skia.ColorWHITE)
        if outline:
            p.setStyle(skia.Paint.kStrokeAndFill_Style)
            p.setStrokeWidth(STROKE)
            p.setStrokeJoin(skia.Paint.kRound_Join)
        for g in glyphs:
            if g["empty"]:
                continue
            ox = g["x"] - g["xoff"]          # pen origin inside the cell
            oy = g["y"] - (g["yoff"] - cap)  # baseline inside the cell
            blob = skia.TextBlob.MakeFromText(g["ch"], font)
            c.drawTextBlob(blob, ox, oy, p)
        img = surf.makeImageSnapshot()
        name = "font_outline.png" if outline else "font.png"
        # keep every pixel white (only alpha varies) so filtering never darkens the edges
        a = img.toarray(colorType=skia.kRGBA_8888_ColorType, alphaType=skia.kUnpremul_AlphaType)
        a[:, :, :3] = 255
        skia.Image.fromarray(a, colorType=skia.kRGBA_8888_ColorType, alphaType=skia.kUnpremul_AlphaType).save(
            os.path.join(ROOT, "assets", name), skia.kPNG)
        print("wrote assets/" + name, ATLAS_W, "x", height)
    out = ["// AUTO-GENERATED by tools/font/make_font.py - edit that script, not this file",
           "#pragma once",
           "struct FontGlyph { short x, y, w, h; float xoff, yoff, adv; };",
           "static const int FONT_FIRST = %d, FONT_COUNT = %d;" % (FIRST, LAST - FIRST + 1),
           "static const float FONT_EM = %d, FONT_CAP = %.2ff;" % (EM, cap),
           "static const FontGlyph FONT_GLYPHS[] = {"]
    for g in glyphs:
        out.append("  {%d, %d, %d, %d, %.2ff, %.2ff, %.2ff},  // %r" % (g["x"], g["y"], g["w"], g["h"], g["xoff"], g["yoff"], g["adv"], g["ch"]))
    out.append("};")
    open(os.path.join(ROOT, "engine", "font_data.h"), "w").write("\n".join(out) + "\n")
    print("wrote engine/font_data.h")


if __name__ == "__main__":
    main()
