// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace thart {
inline int TEX[7] = {-1, -1, -1, -1, -1, -1, -1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[7] = {"turbohorizon/atlas0.png", "turbohorizon/far0.png", "turbohorizon/near0.png", "turbohorizon/far1.png", "turbohorizon/near1.png", "turbohorizon/far2.png", "turbohorizon/near2.png"};
static const int NTEX = 7;
static const nova::Img IMG_PCAR0 = {&TEX[0], 827, 665, 736, 315, 368.0f, 315.0f, 0.5000f};
static const nova::Img IMG_PCAR1 = {&TEX[0], 3, 1010, 736, 315, 368.0f, 315.0f, 0.5000f};
static const nova::Img IMG_PCAR2 = {&TEX[0], 745, 1010, 736, 315, 368.0f, 315.0f, 0.5000f};
static const nova::Img IMG_RIVAL0 = {&TEX[0], 1008, 1331, 323, 160, 161.5f, 160.0f, 1.0000f};
static const nova::Img IMG_RIVAL1 = {&TEX[0], 1569, 665, 287, 228, 143.5f, 228.0f, 1.0000f};
static const nova::Img IMG_RIVAL2 = {&TEX[0], 679, 1331, 323, 168, 161.5f, 168.0f, 1.0000f};
static const nova::Img IMG_RIVAL3 = {&TEX[0], 3, 1331, 332, 189, 166.0f, 189.0f, 1.0000f};
static const nova::Img IMG_PALM0 = {&TEX[0], 920, 3, 315, 591, 157.0f, 591.0f, 1.0000f};
static const nova::Img IMG_PALM1 = {&TEX[0], 579, 3, 335, 593, 165.0f, 593.0f, 1.0000f};
static const nova::Img IMG_ROCK = {&TEX[0], 341, 1331, 332, 177, 166.0f, 177.0f, 1.0000f};
static const nova::Img IMG_MESA = {&TEX[0], 1487, 1010, 548, 265, 274.0f, 265.0f, 1.0000f};
static const nova::Img IMG_CACTUS = {&TEX[0], 1877, 3, 148, 326, 74.0f, 326.0f, 1.0000f};
static const nova::Img IMG_BILL0 = {&TEX[0], 1465, 3, 406, 339, 203.0f, 339.0f, 1.0000f};
static const nova::Img IMG_BILL1 = {&TEX[0], 3, 665, 406, 339, 203.0f, 339.0f, 1.0000f};
static const nova::Img IMG_BILL2 = {&TEX[0], 415, 665, 406, 339, 203.0f, 339.0f, 1.0000f};
static const nova::Img IMG_LAMP = {&TEX[0], 1241, 3, 167, 512, 82.0f, 512.0f, 1.0000f};
static const nova::Img IMG_TOWER0 = {&TEX[0], 291, 3, 282, 643, 141.0f, 643.0f, 1.0000f};
static const nova::Img IMG_TOWER1 = {&TEX[0], 3, 3, 282, 656, 141.0f, 656.0f, 1.0000f};
static const nova::Img IMG_CHEVRON = {&TEX[0], 1862, 665, 137, 194, 68.0f, 194.0f, 1.0000f};
static const nova::Img IMG_BUSH = {&TEX[0], 1337, 1331, 198, 116, 99.0f, 116.0f, 1.0000f};
static const nova::Img IMG_BANNERC = {&TEX[0], 3, 1526, 800, 121, 400.0f, 121.0f, 1.0000f};
static const nova::Img IMG_BANNERS = {&TEX[0], 809, 1526, 800, 121, 400.0f, 121.0f, 1.0000f};
static const nova::Img IMG_POST = {&TEX[0], 1414, 3, 45, 409, 22.5f, 409.0f, 1.0000f};
static const nova::Img IMG_FAR0 = {&TEX[1], 0, 0, 2304, 420, 0, 0, 1.0000f};
static const nova::Img IMG_NEAR0 = {&TEX[2], 0, 0, 2304, 140, 0, 0, 1.0000f};
static const nova::Img IMG_FAR1 = {&TEX[3], 0, 0, 2304, 420, 0, 0, 1.0000f};
static const nova::Img IMG_NEAR1 = {&TEX[4], 0, 0, 2304, 260, 0, 0, 1.0000f};
static const nova::Img IMG_FAR2 = {&TEX[5], 0, 0, 2304, 420, 0, 0, 1.0000f};
static const nova::Img IMG_NEAR2 = {&TEX[6], 0, 0, 2304, 260, 0, 0, 1.0000f};
static const nova::Img* const RIVAL[4] = {&IMG_RIVAL0, &IMG_RIVAL1, &IMG_RIVAL2, &IMG_RIVAL3};
static const nova::Img* const PCAR[3] = {&IMG_PCAR0, &IMG_PCAR1, &IMG_PCAR2};
static const nova::Img* const SCENERY[16] = {&IMG_PALM0, &IMG_PALM1, &IMG_ROCK, &IMG_MESA, &IMG_CACTUS, &IMG_BILL0, &IMG_BILL1, &IMG_BILL2, &IMG_LAMP, &IMG_TOWER0, &IMG_TOWER1, &IMG_CHEVRON, &IMG_BUSH, &IMG_BANNERC, &IMG_BANNERS, &IMG_POST};
}  // namespace thart
