// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace gcart {
inline int TEX[1] = {-1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[1] = {"gemcascade/atlas0.png"};
static const int NTEX = 1;
static const nova::Img IMG_GEM_RUBY = {&TEX[0], 3, 365, 246, 239, 123.0f, 111.0f, 0.5000f};
static const nova::Img IMG_GEM_SAPPHIRE = {&TEX[0], 767, 365, 236, 234, 118.0f, 106.0f, 0.5000f};
static const nova::Img IMG_GEM_EMERALD = {&TEX[0], 1508, 3, 212, 246, 106.0f, 118.0f, 0.5000f};
static const nova::Img IMG_GEM_TOPAZ = {&TEX[0], 1274, 3, 228, 250, 114.0f, 122.0f, 0.5000f};
static const nova::Img IMG_GEM_AMETHYST = {&TEX[0], 1726, 3, 256, 241, 128.0f, 113.0f, 0.5000f};
static const nova::Img IMG_GEM_PEARL = {&TEX[0], 255, 365, 244, 238, 122.0f, 110.0f, 0.5000f};
static const nova::Img IMG_GEM_AMBER = {&TEX[0], 505, 365, 256, 236, 128.0f, 108.0f, 0.5000f};
static const nova::Img IMG_NOVA = {&TEX[0], 1217, 365, 194, 194, 97.0f, 97.0f, 0.5000f};
static const nova::Img IMG_NOVA_SHINE = {&TEX[0], 1009, 365, 202, 202, 101.0f, 101.0f, 0.5000f};
static const nova::Img IMG_FLAME = {&TEX[0], 3, 3, 351, 356, 171.0f, 178.0f, 0.5000f};
static const nova::Img IMG_GLINT = {&TEX[0], 360, 3, 320, 320, 160.0f, 160.0f, 0.5000f};
static const nova::Img IMG_STARMARK = {&TEX[0], 1417, 365, 120, 120, 60.0f, 60.0f, 0.5000f};
static const nova::Img IMG_CURSOR = {&TEX[0], 686, 3, 288, 288, 144.0f, 144.0f, 0.5000f};
static const nova::Img IMG_SELECT = {&TEX[0], 980, 3, 288, 288, 144.0f, 144.0f, 0.5000f};
static const nova::Img IMG_SHARD = {&TEX[0], 1988, 3, 44, 46, 21.0f, 27.0f, 0.5000f};
static const nova::Img* const GEM[7] = {&IMG_GEM_RUBY, &IMG_GEM_SAPPHIRE, &IMG_GEM_EMERALD, &IMG_GEM_TOPAZ, &IMG_GEM_AMETHYST, &IMG_GEM_PEARL, &IMG_GEM_AMBER};
}  // namespace gcart
