// AUTO-GENERATED by an art script - edit the script, not this file
#pragma once
#include "nova.h"
namespace csart {
inline int TEX[4] = {-1, -1, -1, -1};   // one copy shared by every file that includes this
static const char* const TEX_FILES[4] = {"cityshield/atlas0.png", "cityshield/ground.png", "cityshield/skyline.png", "cityshield/skyline_win.png"};
static const int NTEX = 4;
static const nova::Img IMG_CITY0 = {&TEX[0], 595, 3, 290, 286, 145.0f, 273.0f, 0.5000f};
static const nova::Img IMG_CITY1 = {&TEX[0], 891, 3, 290, 286, 145.0f, 273.0f, 0.5000f};
static const nova::Img IMG_CITY2 = {&TEX[0], 299, 3, 290, 289, 145.0f, 276.0f, 0.5000f};
static const nova::Img IMG_CITY3 = {&TEX[0], 1483, 3, 290, 270, 145.0f, 257.0f, 0.5000f};
static const nova::Img IMG_CITY4 = {&TEX[0], 1187, 3, 290, 275, 145.0f, 262.0f, 0.5000f};
static const nova::Img IMG_CITY5 = {&TEX[0], 3, 3, 290, 309, 145.0f, 296.0f, 0.5000f};
static const nova::Img IMG_RUIN0 = {&TEX[0], 1333, 318, 290, 79, 145.0f, 73.0f, 0.5000f};
static const nova::Img IMG_RUIN1 = {&TEX[0], 724, 318, 290, 80, 145.0f, 70.0f, 0.5000f};
static const nova::Img IMG_RUIN2 = {&TEX[0], 3, 430, 290, 77, 145.0f, 68.0f, 0.5000f};
static const nova::Img IMG_RUIN3 = {&TEX[0], 1629, 318, 290, 78, 145.0f, 71.0f, 0.5000f};
static const nova::Img IMG_RUIN4 = {&TEX[0], 299, 430, 290, 71, 145.0f, 65.0f, 0.5000f};
static const nova::Img IMG_RUIN5 = {&TEX[0], 1020, 318, 307, 80, 152.0f, 73.0f, 0.5000f};
static const nova::Img IMG_BASE = {&TEX[0], 43, 318, 250, 98, 125.0f, 93.0f, 0.5000f};
static const nova::Img IMG_BARREL = {&TEX[0], 3, 318, 34, 106, 17.0f, 101.0f, 0.5000f};
static const nova::Img IMG_BASE_RUIN = {&TEX[0], 595, 430, 258, 61, 129.0f, 56.0f, 0.5000f};
static const nova::Img IMG_MISSILE = {&TEX[0], 1957, 318, 85, 30, 41.0f, 15.0f, 0.5000f};
static const nova::Img IMG_AMMO = {&TEX[0], 1925, 318, 26, 64, 13.0f, 64.0f, 0.5000f};
static const nova::Img IMG_BOMBER = {&TEX[0], 299, 318, 213, 95, 113.0f, 46.0f, 0.5000f};
static const nova::Img IMG_SAT = {&TEX[0], 518, 318, 200, 82, 100.0f, 51.0f, 0.5000f};
static const nova::Img IMG_MOON = {&TEX[0], 1779, 3, 250, 250, 125.0f, 125.0f, 0.5000f};
static const nova::Img IMG_GROUND = {&TEX[1], 0, 0, 1920, 220, 0, 0, 1.0000f};
static const nova::Img IMG_SKYLINE = {&TEX[2], 0, 0, 1920, 330, 0, 0, 1.0000f};
static const nova::Img IMG_SKYLINE_WIN = {&TEX[3], 0, 0, 1920, 330, 0, 0, 1.0000f};
static const nova::Img* const CITIES[6] = {&IMG_CITY0, &IMG_CITY1, &IMG_CITY2, &IMG_CITY3, &IMG_CITY4, &IMG_CITY5};
static const nova::Img* const RUINS[6] = {&IMG_RUIN0, &IMG_RUIN1, &IMG_RUIN2, &IMG_RUIN3, &IMG_RUIN4, &IMG_RUIN5};
// the original's ground profile: rows below GROUND_Y where the ground starts, per field column
static const uint8_t GROUND_TOP[320] = {12,11,10,10,9,9,8,8,7,7,6,6,6,5,4,4,3,3,3,2,2,2,2,2,2,2,2,2,2,2,3,3,3,4,4,5,6,6,6,7,7,8,8,9,9,10,10,11,12,13,13,14,15,16,16,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,17,17,17,17,17,17,17,17,17,17,17,17,17,17,18,18,18,18,18,18,18,18,18,16,15,14,13,13,12,11,10,10,9,9,8,8,7,7,6,6,6,5,4,4,3,3,3,2,2,2,2,2,2,2,2,2,2,2,3,3,3,4,4,5,6,6,6,7,7,8,8,9,9,10,10,11,12,13,13,14,15,16,18,18,18,18,17,17,17,17,17,17,17,17,17,17,17,17,17,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,16,16,16,16,16,16,16,16,15,14,13,13,12,11,10,10,9,9,8,8,7,7,6,6,6,5,4,4,3,3,3,2,2,2,2,2,2,2,2,2,2,2,3,3,3,4,4,5,6,6,6,7,7,8,8,9,9,10,10,11};
static const float LAYER_TOP = 860;   // screen row of IMG_GROUND's top edge
// antenna-light positions per city, relative to the city sprite's pivot (screen pixels)
static const int NLIGHTS = 4;
static const float CITY_LIGHTS[6][4][2] = {{{-60.4f, -79.6f}, {37.1f, -75.6f}, {56.9f, -103.4f}, {-999.0f, -999.0f}}, {{-40.0f, -102.5f}, {-12.6f, -62.3f}, {8.6f, -79.2f}, {32.6f, -107.1f}}, {{-61.0f, -97.0f}, {-23.4f, -82.6f}, {-999.0f, -999.0f}, {-999.0f, -999.0f}}, {{-19.2f, -72.1f}, {7.5f, -52.1f}, {61.0f, -73.1f}, {-999.0f, -999.0f}}, {{-41.0f, -62.0f}, {-2.1f, -51.4f}, {18.8f, -87.0f}, {-999.0f, -999.0f}}, {{-27.6f, -71.7f}, {-11.0f, -55.8f}, {17.1f, -81.8f}, {62.7f, -97.4f}}};
}  // namespace csart
